name: Release 🚀

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 📦
        uses: actions/checkout@v2

      - name: Set up Go 🐹
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Extract tag version 🔖
        id: extract_tag
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Set metadata 📝
        run: |
          echo "VERSION=${{ steps.extract_tag.outputs.version }}" >> $GITHUB_ENV
          echo "DESCRIPTION=Over-Engineered Factorial App made in Go." >> $GITHUB_ENV
          echo "AUTHOR=EduardoProfe666" >> $GITHUB_ENV

      - name: Install fyne-cross 🛠️
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Build for Windows (amd64) 🏁
        run: fyne-cross windows -app-id "com.eduardoprofe666.factorialapp" -icon "assets/icon.png"

      - name: Build for Android (arm64) 📱
        run: fyne-cross android -arch arm64 -app-id "com.eduardoprofe666.factorialapp" -icon "assets/icon.png"

      - name: Build for Android (arm) 📱
        run: fyne-cross android -arch arm -app-id "com.eduardoprofe666.factorialapp" -icon "assets/icon.png"

      - name: Create release 📢
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Android (arm64) release assets 📤
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fyne-cross/dist/android-arm64/Factorial-App.apk
          asset_name: Factorial-App-android-arm64.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Windows (amd64) release assets 📤
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fyne-cross/dist/windows-amd64/Factorial-App.exe.zip
          asset_name: Factorial-App-windows-amd64.zip
          asset_content_type: application/zip



      - name: Upload Android (arm) release assets 📤
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fyne-cross/dist/android-arm/Factorial-App.apk
          asset_name: Factorial-App-android-arm.apk
          asset_content_type: application/vnd.android.package-archive
